### ISSUE TITLE
Empty field with v0.10.51

### ISSUE THREAD

**Issue by DrFeelNice** [lostindark/DriverStoreExplorer#85]
Hi Teddy,

With Win7Pro64, the following error appears when sorting the version column (probably due to an empty field).
By the way, the error window is not properly displayed (not resizable).

Regards,

![2019-07-31](https://user-images.githubusercontent.com/51505681/62191661-39deed00-b374-11e9-88d7-ee73810a4316.png)

**Comment by lostindark** [comment]
Can you share the log file?

**Comment by lostindark** [comment]
The exception should be fixed with 91efe20dbb681bbc8ed9e70deb3d8431ecd4a220.
You can try the build with fix here: https://ci.appveyor.com/api/buildjobs/ysjmx3dil62u0jkd/artifacts/Rapr%2Fbin%2FDriverStoreExplorer.v0.10.52.zip

The error window is a system window (probably owned by .net framework), which I don't have a way to control the experience.

**Comment by DrFeelNice** [comment]
Thanks Teddy, v0.10.52 works fine !
